### ISSUE TITLE
Color output for default julia config

### ISSUE THREAD

**Issue by jakebolewski** [JuliaCI/TravisTest.jl#1]
I didn't know where to file an issue, could the default Travis config run the tests with `julia --color=yes`?

**Comment by tkelman** [comment]
We could try adding `--color=yes` to this line https://github.com/travis-ci/travis-build/blob/c1edce660721df096c289f79f35056c191e47a81/lib/travis/build/script/julia.rb#L70, ~~but since `Pkg.test` spawns a new child Julia process I'm not sure if it would make a difference~~ edit: looks like it might work, looking at https://github.com/JuliaLang/julia/blob/457ff03d8aeb936e6f3133e8ba3af49733d58ef1/base/pkg/entry.jl#L694 - should test it first by manually overriding the script contents. Can you track down what is failing on Travis for the default checks in Julia for whether colored output is supported?

**Comment by ghost** [comment]
I agree that we should try to track down what is going wrong with our colour detection, but I am not opposed to forcing it if it turns out to be a more difficult problem than expected.

**Comment by jakebolewski** [comment]
@tkelman I don't quite understand the last sentence.  Where are you guys checking color output?
Julia is only checking if `tput setaf 0` has a return code of 0.

Color output will only be performed when starting up the REPL, so you always have to force it when running a statement from the command line.

**Comment by tkelman** [comment]
The travis script just runs `julia --check-bounds=yes -e "Pkg.test(\"$PKG\")"`, not too much more. I wasn't sure whether `Pkg.test` would propagate a forced color setting to the child julia subprocess that it spawns, but it looks like it does. Just to double-check, are we sure that `tput setaf 0` returns something nonzero on its own in Travis? Any idea why?

**Comment by jakebolewski** [comment]
@tkelman I misunderstood you, that is the check Julia is doing not that it fails in Travis.  We don't spawn the REPL so that check is never performed.

**Comment by tkelman** [comment]
> We don't spawn the REPL so that check is never performed.

Oooh, okay. Yeah we can add `--color=yes` to all the lines where we run julia in `julia.rb` in the travis-build repo. We should also turn on the `coverage=true` keyword argument to `Pkg.test` while we're at it, been meaning to do that for a while.

**Comment by jakebolewski** [comment]
Cool, thanks!

**Comment by tkelman** [comment]
See https://github.com/travis-ci/travis-build/pull/411

**Comment by ghost** [comment]
Thank you @tkelman for handling this.

**Comment by tkelman** [comment]
If they take much longer to respond, maybe open an issue at https://github.com/travis-ci/travis-ci

**Comment by jakebolewski** [comment]
Looks like this just got merged.

**Comment by tkelman** [comment]
Indeed, let us know if you don't see it get rolled out. Not sure what the delay would be, if any.
